version: "3.8"
services:
  web:
    image: processmaker:v${PM_VERSION}
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    ports:
      - ${PM_APP_PORT}:80
      - ${PM_BROADCASTER_PORT}:6001
      - 9001:9001
    volumes:
      - ${PM_DOCKER_SOCK}:/var/run/docker.sock
    links:
      - redis
      - mysql 
    depends_on:
      - mysql
      - redis

  # web_old:
  #   image: processmaker:v${PM_VERSION}
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       PM_VERSION: ${PM_VERSION}
  #   ports:
  #     - ${PM_APP_PORT}:80
  #     - ${PM_BROADCASTER_PORT}:6001
  #     - 9001:9001
  #   environment:
  #     - PM_APP_URL
  #     - PM_APP_PORT
  #     - PM_BROADCASTER_PORT
  #     - DB_DATABASE=processmaker
  #     - PM_CI=false
  #     - CACHE_DRIVER=redis
  #     - REDIS_HOST=redis
  #   volumes:
  #     - ${PM_DOCKER_SOCK}:/var/run/docker.sock
  #     # - storage:/code/pm4/storage
  #   links:
  #     - redis
  #     - mysql 
  #   depends_on:
  #     - mysql
  #     - redis

  redis:
    image: redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: processmaker
      MYSQL_USER: pm
      MYSQL_PASSWORD: pass
    volumes:
      - database:/var/lib/mysql
      
volumes:
  database:
  storage: